server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    #注册到zookeeper地址
    zookeeper:
      connect-string: zookeeper02:2181,zookeeper03:2181,zookeeper04:2181 #zookeeper集群
